## NUMPY

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

## CRUD

### 1.CREATE

In [6]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [7]:
data

array([[[0.04997711, 0.4050585 , 0.37123641, 0.6129778 ],
        [0.9045276 , 0.64988967, 0.16415951, 0.64709736],
        [0.26350537, 0.33293361, 0.69169561, 0.15045996]],

       [[0.69129472, 0.58111035, 0.45910475, 0.23468081],
        [0.69373311, 0.52110853, 0.7899112 , 0.98755271],
        [0.47544296, 0.87181724, 0.86371062, 0.14978569]]])

In [8]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [9]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [10]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [12]:
arr = np.array([[1,2,3,4],[1,2,3,4,]])

In [13]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [14]:
type(arr)

numpy.ndarray

### 2.READ

In [15]:
# attributes
shape = data.shape
size = data.size
types = data.dtype

In [16]:
size

24

In [17]:
shape

(2, 3, 4)

In [18]:
types

dtype('float64')

In [25]:
# slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [20]:
arr

array([[0.04997711, 0.4050585 , 0.37123641, 0.6129778 ],
       [0.9045276 , 0.64988967, 0.16415951, 0.64709736],
       [0.26350537, 0.33293361, 0.69169561, 0.15045996]])

In [24]:
slicer

array([[0.04997711, 0.4050585 , 0.37123641, 0.6129778 ],
       [0.9045276 , 0.64988967, 0.16415951, 0.64709736]])

In [22]:
singleval

0.04997710513575804

### 3.UPDATE

In [26]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [27]:
list1

array([0.28096158, 0.79576028, 0.01156591, 0.25210198, 0.88265652,
       0.0129592 , 0.40142157, 0.67444778, 0.27580073, 0.26751696])

In [28]:
list2

array([0.78151438, 0.8648487 , 0.03309568, 0.87384922, 0.08190584,
       0.59633579, 0.004221  , 0.57563487, 0.9786256 , 0.58682148])

In [29]:
# basic math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
mul = np.multiply(list1, list2)
div = np.divide(list1, list2)
dot = np.dot(list1, list2)

In [30]:
add

array([1.06247596, 1.66060898, 0.04466159, 1.12595121, 0.96456236,
       0.60929499, 0.40564257, 1.25008265, 1.25442633, 0.85433844])

In [31]:
sub

array([-0.5005528 , -0.06908842, -0.02152977, -0.62174724,  0.80075069,
       -0.58337659,  0.39720058,  0.09881291, -0.70282487, -0.31930453])

In [32]:
mul

array([2.19575516e-01, 6.88212240e-01, 3.82781712e-04, 2.20299123e-01,
       7.22947222e-02, 7.72803240e-03, 1.69439869e-03, 3.88235658e-01,
       2.69905659e-01, 1.56984697e-01])

In [33]:
div

array([3.59509164e-01, 9.20115024e-01, 3.49468908e-01, 2.88495976e-01,
       1.07764788e+01, 2.17313740e-02, 9.51011594e+01, 1.17165901e+00,
       2.81824565e-01, 4.55874512e-01])

In [34]:
dot

2.025312826560354

In [36]:
# SAPLEMM
# sqrt, abs, power, log, exp, min, max
sqrt = np.sqrt(25)
ab = np.abs(-1)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxi = np.max(list1)

In [37]:
sqrt

5.0

In [38]:
ab

1

In [39]:
data

array([[[0.04997711, 0.4050585 , 0.37123641, 0.6129778 ],
        [0.9045276 , 0.64988967, 0.16415951, 0.64709736],
        [0.26350537, 0.33293361, 0.69169561, 0.15045996]],

       [[0.69129472, 0.58111035, 0.45910475, 0.23468081],
        [0.69373311, 0.52110853, 0.7899112 , 0.98755271],
        [0.47544296, 0.87181724, 0.86371062, 0.14978569]]])

In [40]:
data[0][0][0] = 2

In [41]:
data

array([[[2.        , 0.4050585 , 0.37123641, 0.6129778 ],
        [0.9045276 , 0.64988967, 0.16415951, 0.64709736],
        [0.26350537, 0.33293361, 0.69169561, 0.15045996]],

       [[0.69129472, 0.58111035, 0.45910475, 0.23468081],
        [0.69373311, 0.52110853, 0.7899112 , 0.98755271],
        [0.47544296, 0.87181724, 0.86371062, 0.14978569]]])

In [42]:
data.sort()
data

array([[[0.37123641, 0.4050585 , 0.6129778 , 2.        ],
        [0.16415951, 0.64709736, 0.64988967, 0.9045276 ],
        [0.15045996, 0.26350537, 0.33293361, 0.69169561]],

       [[0.23468081, 0.45910475, 0.58111035, 0.69129472],
        [0.52110853, 0.69373311, 0.7899112 , 0.98755271],
        [0.14978569, 0.47544296, 0.86371062, 0.87181724]]])

In [43]:
print(data.shape)

(2, 3, 4)


In [44]:
data = data.reshape(2,2,-1)

In [45]:
print(data.shape)

(2, 2, 6)


In [48]:
# append
zeroArr = np.zeros((6))
print(zeroArr)
zeroArr = np.append(zeroArr, [2,3])
print(zeroArr)

[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 2. 3.]


In [49]:
#insert
zeroArr = np.insert(zeroArr, 3, 6)
print(zeroArr)

[0. 0. 0. 6. 0. 0. 0. 2. 3.]


### 4.DELETE

In [50]:
data 

array([[[0.37123641, 0.4050585 , 0.6129778 , 2.        , 0.16415951,
         0.64709736],
        [0.64988967, 0.9045276 , 0.15045996, 0.26350537, 0.33293361,
         0.69169561]],

       [[0.23468081, 0.45910475, 0.58111035, 0.69129472, 0.52110853,
         0.69373311],
        [0.7899112 , 0.98755271, 0.14978569, 0.47544296, 0.86371062,
         0.87181724]]])

In [51]:
np.delete(data, 0, axis=1)

array([[[0.64988967, 0.9045276 , 0.15045996, 0.26350537, 0.33293361,
         0.69169561]],

       [[0.7899112 , 0.98755271, 0.14978569, 0.47544296, 0.86371062,
         0.87181724]]])

In [52]:
np.save('new array', data)

In [53]:
test = np.load('new array.npy')

In [54]:
test

array([[[0.37123641, 0.4050585 , 0.6129778 , 2.        , 0.16415951,
         0.64709736],
        [0.64988967, 0.9045276 , 0.15045996, 0.26350537, 0.33293361,
         0.69169561]],

       [[0.23468081, 0.45910475, 0.58111035, 0.69129472, 0.52110853,
         0.69373311],
        [0.7899112 , 0.98755271, 0.14978569, 0.47544296, 0.86371062,
         0.87181724]]])

# END